drop table IF EXISTS PUBLIC.compilations_events;
drop table IF EXISTS PUBLIC.compilations;
drop table IF EXISTS PUBLIC.requests;
drop table IF EXISTS PUBLIC.EVENTS;
drop table IF EXISTS PUBLIC.USERS;
drop table IF EXISTS PUBLIC.CATEGORIES;
drop table IF EXISTS PUBLIC.LOCATIONS;

create TABLE IF NOT EXISTS users(
  id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email   VARCHAR(254) NOT NULL UNIQUE,
  name    VARCHAR(250) NOT NULL
);

create TABLE IF NOT EXISTS categories(
  id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name    VARCHAR(250) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS locations(
  id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lat    FLOAT NOT NULL,
  lon    FLOAT NOT NULL
);

create TABLE IF NOT EXISTS events(
id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
annotation         VARCHAR(2000) NOT NULL,
category_id        BIGINT NOT NULL REFERENCES categories(id),
confirmed_requests INT NOT NULL,
created_on         TIMESTAMP  WITHOUT TIME ZONE NOT NULL,
description        VARCHAR(7000) NOT NULL,
event_date         TIMESTAMP  WITHOUT TIME ZONE NOT NULL,
initiator_id       BIGINT NOT NULL REFERENCES users(id) ON delete SET NULL,
location_id        BIGINT NOT NULL REFERENCES locations(id) ON delete SET NULL,
paid               BOOLEAN,
participant_limit  INTEGER DEFAULT 0,
published_on       TIMESTAMP  WITHOUT TIME ZONE,
request_moderation BOOLEAN DEFAULT TRUE,
state              VARCHAR(25) NOT NULL,
title              VARCHAR(120) NOT NULL
);

create TABLE IF NOT EXISTS requests(
id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created   TIMESTAMP    NOT NULL,
event     BIGINT REFERENCES events(id) ON delete CASCADE,
requester BIGINT REFERENCES users(id) ON delete CASCADE,
status    VARCHAR(255) NOT NULL
);

create TABLE IF NOT EXISTS compilations(
id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pinned    BOOLEAN,
title     VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS compilations_events(
compilations_id  BIGINT REFERENCES compilations(id) ON delete CASCADE,
events_id        BIGINT REFERENCES events(id) ON delete CASCADE,
PRIMARY KEY(compilations_id, events_id)
);

create TABLE IF NOT EXISTS comments(
id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
text        VARCHAR(2000) NOT NULL,
event       BIGINT REFERENCES events(id) ON delete CASCADE,
author      BIGINT REFERENCES users(id) ON delete CASCADE,
created     TIMESTAMP  NOT NULL,
status      VARCHAR(255) NOT NULL,
edit_time   TIMESTAMP
);

create TABLE IF NOT EXISTS likes(
id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
comment   BIGINT REFERENCES comments(id) ON delete CASCADE,
is_like   BOOLEAN,
liker     BIGINT REFERENCES users(id) ON delete CASCADE,
created   TIMESTAMP  NOT NULL
);