drop table IF EXISTS PUBLIC.USERS;
drop table IF EXISTS PUBLIC.CATEGORIES;
drop table IF EXISTS PUBLIC.LOCATIONS;

create TABLE IF NOT EXISTS users(
  id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email   VARCHAR(254) NOT NULL UNIQUE,
  name    VARCHAR(250) NOT NULL
);

create TABLE IF NOT EXISTS categories(
  id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name    VARCHAR(250) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS locations(
  id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lat    REAL NOT NULL,
  lon    REAL NOT NULL
);