CREATE TABLE IF NOT EXISTS stats(
  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name_app     VARCHAR(100) NOT NULL,
  uri          VARCHAR(100) NOT NULL,
  ip_user      VARCHAR(50) NOT NULL,
  created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);